name: search/rand/50
seed: 1

log_level: info
report_interval: 10
eval_interval: 50
save_interval: 50

data_path: data/rand
train_sets:
  - name: 50-213
    samples: 2000
    max_tries: 5
    max_flips: 750
    iterations: 10000

eval_set:
  name: 100-426
  samples: 5
  max_tries: 5
  max_flips: 1500

model_path: a2c_results/search/rand/25/model_best.pth

gnn_hidden_size: 32
readout_hidden_size: 64

cycles: 1
optimizer: RMSprop
lr: 0.0001
lr_milestones: [200, 500, 1000, 5000]
lr_decay: 0.8

method: a2c
a2c_n: 35
discount: 0.99
walk_prob: 0.5
